- name: configure dispatch
  hosts: dispatch
  become: yes

  tasks:

    - name: Install golang
      ansible.builtin.dnf:
        name: golang
        state: present

    - name: Create roboshop system user
      ansible.builtin.user:
        name: roboshop
        system: yes
        home: /app
        shell: /sbin/nologin
        comment: "roboshop system user"

    - name: Create app directory
      ansible.builtin.file:
        path: /app
        state: directory
        owner: roboshop
        group: roboshop
        mode: '0755'

    - name: Download the application code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/dispatch-v3.zip
        dest: /tmp/dispatch.zip

    - name: Clean old app content (important)
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Recreate app directory
      ansible.builtin.file:
        path: /app
        state: directory
        owner: roboshop
        group: roboshop
        mode: '0755'

    - name: Unarchive the code
      ansible.builtin.unarchive:
        src: /tmp/dispatch.zip
        dest: /app
        remote_src: yes
        

    - name: Fix ownership
      ansible.builtin.file:
        path: /app
        owner: roboshop
        group: roboshop
        recurse: yes

    - name: Download Go dependencies
      ansible.builtin.command: go mod tidy
      args:
        chdir: /app
      become_user: roboshop

    - name: Build the application
      ansible.builtin.command: go build
      args:
        chdir: /app
      become_user: roboshop

    - name: Copy dispatch service file
      ansible.builtin.copy:
        src: dispatch.service
        dest: /etc/systemd/system/dispatch.service

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start dispatch service
      ansible.builtin.service:
        name: dispatch
        enabled: yes
        state: started