- name: mongodb configuration
  hosts: mongodb
  become: yes
  tasks:
  - name: Copy repo file with owner and permissions
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
    
  - name: MongoDB Installation
    ansible.builtin.dnf:
      name: mongodb-org
      state: present
  
  
  - name: Updating listen address
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: 127.0.0.1 
      replace: 0.0.0.0

  - name: MongoDB Service Start
    ansible.builtin.service:
      name: mongod
      enabled: yes
      state: started

  - name: Download MongoDB schema
    get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/mongodb.zip
      dest: /tmp/mongodb.zip

  - name: Extract schema
    unarchive:
      src: /tmp/mongodb.zip
      dest: /app
      remote_src: yes

  - name: Load catalogue schema
    shell: mongo </app/schema/catalogue.js
    when: catalogue_loaded is not defined

  - name: Load users schema
    shell: mongo </app/schema/users.js
  
  - name: Load catalogue schema
    shell: mongo --host mongodb-dev.rk1214.in </app/schema/catalogue.js

  - name: Load users schema
    shell: mongo --host mongodb-dev.rk1214.in </app/schema/users.js
  